# Generated by Django 4.2.16 on 2024-11-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="yhbchd",
            name="yejcx",
        ),
        migrations.AddField(
            model_name="yhbchd",
            name="yejcx23",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="yhbchd",
            name="bcndjd",
            field=models.BigIntegerField(blank=True),
        ),
    ]
