# Generated by Django 4.2.16 on 2024-11-26 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_yhbchd_yejcx_yhbchd_yejcx23_and_more"),
        ("users", "0002_alter_user_first_name_alter_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rel_yhbchd_1_1",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_rel_yhbchd_1_1",
                to="home.yhbchd",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="rel_yhbchd_n_n",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="user_rel_yhbchd_n_n",
                to="home.yhbchd",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="rel_yhbchd_n_n_1",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="user_rel_yhbchd_n_n_1",
                to="home.yhbchd",
            ),
        ),
    ]
